# Generated by Django 5.1.7 on 2025-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_city_student_password_remove_student_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
